# Generated by Django 6.0.7 on 2026-07-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["name"],
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
        migrations.AddField(
            model_name="teammember",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teammember",
            name="google_scholar",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="linkedin",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="personal_website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="research_interest",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="researchgate",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
