# Generated by Django 6.0.7 on 2026-07-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_teammember_options_teammember_featured_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("description", models.TextField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ["-published_date"],
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-year"],
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
        ),
        migrations.AlterModelOptions(
            name="researcharea",
            options={
                "ordering": ["title"],
                "verbose_name": "Research Area",
                "verbose_name_plural": "Research Areas",
            },
        ),
    ]
