# Generated by Django 6.0.7 on 2026-07-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_gallery_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="category",
            field=models.CharField(
                choices=[
                    ("Research", "Research"),
                    ("Laboratory", "Laboratory"),
                    ("Conference", "Conference"),
                    ("Workshop", "Workshop"),
                    ("Event", "Event"),
                    ("Achievement", "Achievement"),
                ],
                default="Research",
                max_length=50,
            ),
        ),
    ]
