# Generated by Django 6.0.7 on 2026-07-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Viksit Bharat Research Lab", max_length=200
                    ),
                ),
                ("tagline", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("linkedin", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                (
                    "footer_text",
                    models.CharField(default="All Rights Reserved.", max_length=300),
                ),
            ],
            options={
                "verbose_name": "Website Settings",
                "verbose_name_plural": "Website Settings",
            },
        ),
    ]
