# Generated by Django 6.0.7 on 2026-07-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sitesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Award", "Award"),
                            ("Grant", "Grant"),
                            ("Patent", "Patent"),
                            ("Recognition", "Recognition"),
                            ("Competition", "Competition"),
                            ("Publication", "Publication"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="achievements/"),
                ),
                ("year", models.PositiveIntegerField()),
                ("featured", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["-year"],
            },
        ),
    ]
