# Generated by Django 6.0.7 on 2026-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_achievement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["display_order"],
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
            },
        ),
        migrations.AddField(
            model_name="teammember",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
