# Generated by Django 6.0.7 on 2026-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_achievement_options_alter_gallery_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="orcid",
            field=models.URLField(
                blank=True, help_text="e.g. https://orcid.org/0000-0000-0000-0000"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="team_group",
            field=models.CharField(
                choices=[
                    ("Leadership", "Leadership"),
                    ("Research Team", "Research Team"),
                    ("Technical Team", "Technical Team"),
                    ("Advisory Board", "Advisory Board"),
                ],
                default="Technical Team",
                max_length=50,
            ),
        ),
    ]
